### ISSUE TITLE
CNAME

### ISSUE THREAD

**Issue by doismellburning** [PyconUK/2020.pyconuk.org#3]
@ghickman Could you CNAME `2020.pyconuk.org` to `goofy-swanson-b28c12.netlify.com.` please? (Or equivalent as appropriate!)

**Comment by ghickman** [comment]
CNAME added.  I'm getting a 404 when checking it though, does netlify need to be told about it?

Do you need any DNS changes to support HTTPS with netlify?

**Comment by doismellburning** [comment]
@ghickman Thank you!

> I'm getting a 404 when checking it though, does netlify need to be told about it?

Yep, and has been, cheers :)

> Do you need any DNS changes to support HTTPS with netlify?

Nope! 😀 😀 😀  https://2020.pyconuk.org/

(Ignore the lies about GitHub there)
